### ISSUE TITLE
messaging_example exception

### ISSUE THREAD

**Issue by a251115100** [mozilla/geckoview#108]
GeckoConsole: [JavaScript Error: "this.manifest is null" {file: "resource://gre/modules/Extension.jsm" line: 1110}]

An error occurred while registering the WebExtension resource://android/assets/messaging/: TypeError: this.manifest is null.

**Comment by agi90** [comment]
Hi @a251115100, thanks for the bug report, what version of GeckoView and device are you using?

**Comment by a251115100** [comment]
I can't duplicate that any more,Maybe I've configured something wrong.
