### ISSUE TITLE
Can i use GeckoView for my commercial app?

### ISSUE THREAD

**Issue by tmdwns7809** [mozilla/geckoview#110]
Can i use this geckoview engine for my commercial web browser app and make some benefit?
Where can i see the license to find allowed permissions?

**Comment by snorp** [comment]
I believe so, yes. Most of Gecko is licensed under MPL2, which allows this[1]. Other parts of the code are LGPL, GPL, or other licenses which are MPL2 compatible[2]

[1] https://www.mozilla.org/en-US/MPL/2.0/FAQ/
[2] https://hg.mozilla.org/mozilla-central/raw-file/tip/toolkit/content/license.html
