### ISSUE TITLE
Select, DropDown menus and DatePickers not working 

### ISSUE THREAD

**Issue by nilac8991** [mozilla/geckoview#112]
Hello, I am trying to implement GeckoView into an application of mine and i can't find a way at all to make the dropdown menus working. 

Is it there a flag or something to add among the settings before initialising the GeckoSession? 
I found out a similar issue related to Focus here: 
https://github.com/mozilla-mobile/focus-android/issues/4396

Gecko Version : `org.mozilla.geckoview:geckoview-nightly:73.0.20191218091614`

Is there a way to fix this or is it an actual problem inside the source code that still need to be fixed?

Thanks!

**Comment by snorp** [comment]
This is handled in the app by implementing `GeckoSession.PromptDelegate`[1]. We have one in the example app[2] that you may be able to use.

[1] https://mozilla.github.io/geckoview/javadoc/mozilla-central/org/mozilla/geckoview/GeckoSession.PromptDelegate.html
[2] https://searchfox.org/mozilla-central/source/mobile/android/geckoview_example/src/main/java/org/mozilla/geckoview_example/BasicGeckoViewPrompt.java

**Comment by nilac8991** [comment]
Yes, I saw that in Firefox Focus afterwards how it was fixed, thanks for the quick answer!
