### ISSUE TITLE
GeckoView crashes in Shared Element Transition

### ISSUE THREAD

**Issue by tmbenhura** [mozilla/geckoview#121]
GeckoView crashes when used in shared element transitions. The transition may occur on the first 2 or so tries, after which the application crashes. Logcat does not provide any useful information as the app is kill instantly.

Specifically, I was using a MaterialContainerTransform transition from the material.io android components.

**Comment by agi90** [comment]
Hello @tmbenhura , thanks for the report! Please open a bug at https://bugzilla.mozilla.org/enter_bug.cgi?product=GeckoView&component=General and attach a sample app to reproduce this problem.
