### ISSUE TITLE
Gradle Configuration Ambiguity

### ISSUE THREAD

**Issue by wilsonp3** [mozilla/geckoview#126]
When adding GeckoView implementations to the dependencies, My gradle fails to sync when I try to add this into dependencies: 
implementation "org.mozilla.geckoview:geckoview-${geckoviewChannel}:${geckoviewVersion}"

I believe it is because I have to revplace geckoviewChannel and geckoviewVersion, but I can't find what I'm supposed to replace them with.

**Comment by agi90** [comment]
If you want the latest stable version you can see here: https://maven.mozilla.org/?prefix=maven2/org/mozilla/geckoview/geckoview/

e.g. for GeckoView 75 it would be

`org.mozilla.geckoview:geckoview:75.0.20200403170909`
