### ISSUE TITLE
Change about:config values inside code

### ISSUE THREAD

**Issue by safe-bug** [mozilla/geckoview#127]
Hello
I want to change about:config values inside my android code and without using UI, how is it possible to do?

**Comment by snorp** [comment]
It's currently not possible with the public API. We've resisted this in order to be able to limit the number of configurations we need to support.

What prefs do you want to change? For some things, it might make sense to expose them via `GeckoRuntimeSettings`.

**Comment by safe-bug** [comment]
@snorp Isn't it possible in other way than UI? for example with the config file?
I need several prefs but for example I need devPixelsPerPx.

**Comment by snorp** [comment]
> @snorp Isn't it possible in other way than UI? for example with the config file?
> I need several prefs but for example I need devPixelsPerPx.

For `layout.css.devPixelsPerPx` I think it would be reasonable to have a `GeckoRuntimeSetting` for this.

You can use the config file to set prefs, yes. It's not a very good option for an app you want to ship, though.

**Comment by safe-bug** [comment]
Thanks @snorp , config file did work out!

**Comment by dimaslanjaka** [comment]
> > @snorp Isn't it possible in other way than UI? for example with the config file?
> > I need several prefs but for example I need devPixelsPerPx.
> 
> For `layout.css.devPixelsPerPx` I think it would be reasonable to have a `GeckoRuntimeSetting` for this.
> 
> You can use the config file to set prefs, yes. It's not a very good option for an app you want to ship, though.

can you provide an example for disable mediapeer ?
