### ISSUE TITLE
Dedicated GeckoView CookieManager and Cache Storage?

### ISSUE THREAD

**Issue by tonyofrancis** [mozilla/geckoview#129]
Thanks for providing the Android community with such a wonderful alternative! I have been working on a project that needs GeckoView!

My question is: Does GeckoView support the case where a user can be signed into a domain account (gmail for example) in one GeckoView, and sign into another gmail account in a different GeckoView. Both GeckoView instances should NOT share account information such as cookies caches and other data that might identify the accounts. 
Each GeckoView would in theory have their own CookieManager and caches. Is this possible?

Thanks!

**Comment by agi90** [comment]
Hi @tonyofrancis , yes we do support that. Just set a custom `contextId` on the session for each account and GeckoView will separate cookies, session storage, etc. https://mozilla.github.io/geckoview/javadoc/mozilla-central/org/mozilla/geckoview/GeckoSessionSettings.Builder.html#contextId-java.lang.String-

**Comment by tonyofrancis** [comment]
Thanks!

**Comment by dimaslanjaka** [comment]
> Hi @tonyofrancis , yes we do support that. Just set a custom `contextId` on the session for each account and GeckoView will separate cookies, session storage, etc. https://mozilla.github.io/geckoview/javadoc/mozilla-central/org/mozilla/geckoview/GeckoSessionSettings.Builder.html#contextId-java.lang.String-

How to delete unused contextId folder from app data to reduce app data size ?

**Comment by cellojaan** [comment]
> Thanks for providing the Android community with such a wonderful alternative! I have been working on a project that needs GeckoView!
> 
> My question is: Does GeckoView support the case where a user can be signed into a domain account (gmail for example) in one GeckoView, and sign into another gmail account in a different GeckoView. Both GeckoView instances should NOT share account information such as cookies caches and other data that might identify the accounts. Each GeckoView would in theory have their own CookieManager and caches. Is this possible?
> 
> Thanks!

Can you share an example please for it?

**Comment by dimaslanjaka** [comment]
@cellojaan based on my previous project, i used below codes

```kotlin
 val settings = GeckoSessionSettings.Builder()
       .usePrivateMode(true)
       .useTrackingProtection(true)
       .userAgentMode(USER_AGENT_MODE_MOBILE)
       .userAgentOverride("") 
       .suspendMediaWhenInactive(true)
       .allowJavascript(true)
       .contextId("PROFILE NAME")
```

**Comment by cellojaan** [comment]
> @cellojaan based on my previous project, i used below codes
> 
> ```kotlin
>  val settings = GeckoSessionSettings.Builder()
>        .usePrivateMode(true)
>        .useTrackingProtection(true)
>        .userAgentMode(USER_AGENT_MODE_MOBILE)
>        .userAgentOverride("") 
>        .suspendMediaWhenInactive(true)
>        .allowJavascript(true)
>        .contextId("PROFILE NAME")
> ```

And after ```  .contextId("PROFILE NAME") ``` we can get cookies from CookieManager?

**Comment by dimaslanjaka** [comment]
> And after ` .contextId("PROFILE NAME")` we can get cookies from CookieManager?

it's just to differentiate cookies and sessions between different geckoviews (system profiles). to retrieve cookies from geckoview, doesn't seem to be this thread. it's just to differentiate browser sessions.

**Comment by cellojaan** [comment]
> > And after ` .contextId("PROFILE NAME")` we can get cookies from CookieManager?
> 
> it's just to differentiate cookies and sessions between different geckoviews (system profiles). to retrieve cookies from geckoview, doesn't seem to be this thread. it's just to differentiate browser sessions.

Than GeckoView not for us. We need to see user cookies when login to my website for verify if user logged in.
