### ISSUE TITLE
[question] How to inject javascript and interact with it?

### ISSUE THREAD

**Issue by cromefire** [mozilla/geckoview#130]
In webview one can inject JavaScript by running:
```kotlin
webview.evaluateJavascript(script) {
    // ...
}
```

and then communicate with it by having something like this for js -> native:
_Native:_
```kotlin
class NativeConnector {
    @JavascriptInterface
    fun print(a: string) {
        println(a)
    }
}

val connector = NativeConnector()

webview.addJavascriptInterface(connector, "nativeConnector")
```
_JS:_
```typescript
nativeConnector.print("abc")
```

And the other way around (native -> js):
_JS:_
```typescript
window.print = (a) => console.log(a);
```
_Native:_
```kotlin
webview.evaluateJavascript("window.print(\"abc\")") {
    // ...
}
```

Is there anyway to communicate like this in geckoview too?

**Comment by agi90** [comment]
Hello. We use the WebExtension API to inject javascript into pages, follow this guide: https://mozilla.github.io/geckoview/consumer/docs/web-extensions

**Comment by agi90** [comment]
There's a complete example here: https://searchfox.org/mozilla-central/search?q=&path=mobile%2Fandroid%2Fexamples%2Fmessaging_example

**Comment by cromefire** [comment]
Okay thanks

**Comment by HysonHou** [comment]
I read the example code and doc , geckoview no the api like Android evaluateJavascript() to call JS code.
Maybe you can add it on the next version.

**Comment by cromefire** [comment]
As they describes above, the way they go about this (which I think is quite a nice design) is you create a web extension and then the page and the web extension can talk and the web extension and the app can talk via ipc.

This is a bit more work, but seems like a good architecture imo as the web extensions have quite a large and mature API at their disposal.

**Comment by HysonHou** [comment]
> 
> 
> As they describes above, the way they go about this (which I think is quite a nice design) is you create a web extension and then the page and the web extension can talk and the web extension and the app can talk via ipc.
> 
> This is a bit more work, but seems like a good architecture imo as the web extensions have quite a large and mature API at their disposal.

yes , I need to do ipc. at the example backgroud.js no way push message to brower.window(html file) . do you have some good way ? I check document and think many times. but have not success.
