### ISSUE TITLE
the page crashed using Autofill GeckoView(org.mozilla.geckoview:geckoview:80.0.20200903001900)

### ISSUE THREAD

**Issue by a251115100** [mozilla/geckoview#148]
E/AndroidRuntime( 6225): java.lang.ClassCastException: org.mozilla.gecko.util.GeckoBundle cannot be cast to java.lang.String
E/AndroidRuntime( 6225): 	at org.mozilla.gecko.util.GeckoBundle.getString(GeckoBundle.java:343)
E/AndroidRuntime( 6225): 	at org.mozilla.gecko.util.GeckoBundle.getString(GeckoBundle.java:354)
E/AndroidRuntime( 6225): 	at org.mozilla.geckoview.Autofill$Node$Builder.<init>(Autofill.java:789)
E/AndroidRuntime( 6225): 	at org.mozilla.geckoview.Autofill$Support.addNode(Autofill.java:1099)
E/AndroidRuntime( 6225): 	at org.mozilla.geckoview.Autofill$Support.handleMessage(Autofill.java:994)
E/AndroidRuntime( 6225): 	at org.mozilla.gecko.EventDispatcher$3.run(EventDispatcher.java:356)
E/AndroidRuntime( 6225): 	at android.os.Handler.handleCallback(Handler.java:883)
E/AndroidRuntime( 6225): 	at android.os.Handler.dispatchMessage(Handler.java:100)
E/AndroidRuntime( 6225): 	at android.os.Looper.loop(Looper.java:224)
E/AndroidRuntime( 6225): 	at android.app.ActivityThread.main(ActivityThread.java:7562)
E/AndroidRuntime( 6225): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime( 6225): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:539)
E/AndroidRuntime( 6225): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)

**Comment by eamsen** [comment]
This is fixed in GV 84 and pending approval for 83.
See https://bugzilla.mozilla.org/show_bug.cgi?id=1671137.
