### ISSUE TITLE
how to set up http/https proxy at android?

### ISSUE THREAD

**Issue by dujianchi** [mozilla/geckoview#154]
how to set up http/https proxy at android?

**Comment by dujianchi** [comment]
I'm using those code for set up proxy:
```
PrefsHelper.setPref("network.proxy.type", 1) 
PrefsHelper.setPref("network.proxy.http", host) 
PrefsHelper.setPref("network.proxy.http_port", port) 
PrefsHelper.setPref("network.proxy.ssl", host)
PrefsHelper.setPref("network.proxy.ssl_port", port) 
```
but https proxy certificate is not trusted, how to ignore it ? I got a blank screen now...

**Comment by dujianchi** [comment]
try to set [network security configuration](https://developer.android.com/training/articles/security-config), still not working.... really need help 😭

**Comment by agi** [comment]
Hi there! Unfortunately proxy configuration is not currently supported in GeckoView. You can track https://bugzilla.mozilla.org/show_bug.cgi?id=1525486 for that.

**Comment by dimaslanjaka** [comment]
> I'm using those code for set up proxy:
> 
> ```
> PrefsHelper.setPref("network.proxy.type", 1) 
> PrefsHelper.setPref("network.proxy.http", host) 
> PrefsHelper.setPref("network.proxy.http_port", port) 
> PrefsHelper.setPref("network.proxy.ssl", host)
> PrefsHelper.setPref("network.proxy.ssl_port", port) 
> ```
> 
> but https proxy certificate is not trusted, how to ignore it ? I got a blank screen now...

where `PrefsHelper` came from ? can i fork the class?
