### ISSUE TITLE
Setting to allow automatic media playback

### ISSUE THREAD

**Issue by schulzjona** [mozilla/geckoview#156]
Hello, is there any way to change the configuration so that a video with the html tag "autoplay" can be played automatically when the page is loaded?

I have already tried a few things but nothing works.

I use geckoview for a kind of "kiosk" app and there I can't trust that there is always someone to click "play" when the content is updated.

Any ideas how I could solve this problem?

Thanks in advance

Translated with www.DeepL.com/Translator (free version)

**Comment by giri-qs** [comment]
@schulzjona How did you enabled auto play?

**Comment by schulzjona** [comment]
@giri-qs I am loading the following preference during the inital setup of my geckoview instance
`user_pref("media.geckoview.autoplay.request", false);`

I think that was the setting that i changed and after that it worked.

Hope it helps you

**Comment by schulzjona** [comment]
@giri-qs That string needs to be placed in a "user.js" file in the geckoview profile that gets generated automatically when you start your application. On Android it should be found in the files directory of your app

**Comment by quarrysoft** [comment]
> @giri-qs That string needs to be placed in a "user.js" file in the geckoview profile that gets generated automatically when you start your application. On Android it should be found in the files directory of your app

Under assets directory?

**Comment by schulzjona** [comment]
@quarrysoft sorry for the late response, had a lot going on

![image](https://user-images.githubusercontent.com/20225781/213714991-0de11e19-7974-4f7c-afee-781a39418065.png)

You have to edit it here.

You can use this function to resolve the profile string
```
private String getGeckoProfileString() {
        try {
            String line;
            Process process = Runtime.getRuntime().exec("ls /data/data/app.package.name/files/mozilla/");
            InputStream stderr = process.getErrorStream();

            BufferedReader br = new BufferedReader(new InputStreamReader(process.getInputStream()));
            while ((line = br.readLine()) != null) {
                if (line.length() > 8) {
                    String tmp = line.substring(line.length() - 8);
                    if (tmp.equals(".default")) {
                        return line;
                    }
                }
            }

            br.close();
            br = new BufferedReader(new InputStreamReader(stderr));
            while ((line = br.readLine()) != null) {
                Log.e("[Error]", line);
            }
            br.close();

            process.waitFor();
            process.destroy();
        } catch (Exception ex) {
            Log.e("[Error]", ex.getMessage());
        }
        return "error";
    }
```

Be aware that you need to fully launch the webview once, in order to have geckoview generate the profile
