### ISSUE TITLE
background.js How to dispatch message to html document or windows? can provide some example code? 

### ISSUE THREAD

**Issue by HysonHou** [mozilla/geckoview#159]
[question] How to inject javascript and interact with it? #130

**Comment by HysonHou** [comment]
from 14 Aug 2020，the repository no reply for 7 months , it 's un maintrained?

**Comment by fluffyemily** [comment]
I'm sorry, I think we just missed this one. You can find all the documentation about how to interact with javascript through Web Extensions on our documentation site: https://firefox-source-docs.mozilla.org/mobile/android/geckoview/consumer/web-extensions.html

**Comment by HysonHou** [comment]
I have read it, it just support dispach message from Brower to Native，Native to Brower just adapt on background.js , but it not dispach to Brower inner DOM or Window . you have plan to support it ? I think it nessary for geckoview. maybe you can refer to Android WebView.

**Comment by owlishDeveloper** [comment]
@Hynsn can you tell us more about what you're trying to do?

**Comment by agi** [comment]
@Hynsn you can use `window.postMessage` and `window.addEventListener` to interact with a web page: https://stackoverflow.com/a/11431812/1020817

see also https://developer.mozilla.org/en-US/docs/Web/API/Window/postMessage

**Comment by HysonHou** [comment]
> 
> 
> @Hynsn can you tell us more about what you're trying to do?

I use html5 Worker obj to dispatch Message to Window , see :
[https://github.com/Hynsn/TestDemo/blob/master/app/src/main/assets/webmessage.html](https://github.com/Hynsn/TestDemo/blob/master/app/src/main/assets/webmessage.html)
I just hope same use-way like Android Webview . But it's different on the geckoview at background.js . I test background.js not allow get Window , so not finish message to Window .
[https://github.com/Hynsn/TestDemo/blob/master/app/src/main/java/com/example/webview/WebviewActivity.java](https://github.com/Hynsn/TestDemo/blob/master/app/src/main/java/com/example/webview/WebviewActivity.java)
I think  @agi not understudand my problem , it just adapt run on Brower js runtime . I want reverse  interact form Android native to webview.

**Comment by a251115100** [comment]
https://github.com/a251115100/geckoview-jsdemo
this is a simple demo show js call native and native call js

**Comment by owlishDeveloper** [comment]
@Hynsn for messaging from Android to js we have `MessageDelegate` class

**Comment by HysonHou** [comment]
> https://github.com/a251115100/geckoview-jsdemo
> this is a simple demo show js call native and native call js
这个demo和官网的demo类似，我想知道如何将conten.js里面回调接受到的数据更新到具体的dom上面，比如刷到input内容

**Comment by a251115100** [comment]
> > https://github.com/a251115100/geckoview-jsdemo
> > this is a simple demo show js call native and native call js
> > 这个demo和官网的demo类似，我想知道如何将conten.js里面回调接受到的数据更新到具体的dom上面，比如刷到input内容

你可以在conten.js里面使用window.eval("document.getElementById('name1').value='值'");eval方法能执行js代码

**Comment by HysonHou** [comment]
> > > https://github.com/a251115100/geckoview-jsdemo
> > > this is a simple demo show js call native and native call js
> > > 这个demo和官网的demo类似，我想知道如何将conten.js里面回调接受到的数据更新到具体的dom上面，比如刷到input内容
> 
> 你可以在conten.js里面使用window.eval("document.getElementById('name1').value='值'");eval方法能执行js代码

soga，还有其他方法吗 这种方式感觉不是很好
