### ISSUE TITLE
APK size issue

### ISSUE THREAD

**Issue by arvindkumar98** [mozilla/geckoview#166]
I have implemented geckoview in my android application and it  fulfilled my browser requirement that i wanted to get but it raised apk size from 50MB to 283MB. It's thing of concerned for me that how will i upload my app on play store. Please  help me to resolve this issue.

**Comment by agi** [comment]
Hi there! GeckoView contains binaries for all four architectures (x86, x86_64, arm, aarch64). For a one architecture APK GeckoView should add about ~50MB to the APK size. The Play Store should be able to understand this without any intervention from you. Please reopen if you have further issues.

**Comment by ghost** [comment]
after adding geckoview my apk size is around 550 MB . any solutions ?

**Comment by EgorSigolaev** [comment]
> Hi there! GeckoView contains binaries for all four architectures (x86, x86_64, arm, aarch64). For a one architecture APK GeckoView should add about ~50MB to the APK size. The Play Store should be able to understand this without any intervention from you. Please reopen if you have further issues.

Hi. I've tested GeckoView in the sample project.
Dependency: org.mozilla.geckoview:geckoview:125.0.20240425211020

Build release settings: 
`buildTypes {
        release {
            isMinifyEnabled = true
            isShrinkResources = true
            proguardFiles(getDefaultProguardFile("proguard-android-optimize.txt"), "proguard-rules.pro")
        }
    }`

Output: Release aab file with size 215 MB.

Then I decided to check a size of aab for each architecture.
`bundletool build-apks --device-spec=config.json --bundle=app-release.aab --output=app-release.apks`

**base-arm64_v8a.apk**: 139.9 MB
**base-armeabi_v7a.apk**: 106.1 MB
**base-x86.apk**: 167.4 MB
**base-x86_64.apk**: 154.2 MB

So, these sizes are not even close as +50 MB, even 106.1 MB is too much (despite that the project was with just GeckoView dependency). How can I decrease the size of aab?

**Comment by ghost** [comment]
> Hi there! GeckoView contains binaries for all four architectures (x86, x86_64, arm, aarch64). For a one architecture APK GeckoView should add about ~50MB to the APK size. The Play Store should be able to understand this without any intervention from you. Please reopen if you have further issues.

when we created APK file the total size is 500+ MB . then i extracted the apk file using WinRAR and i saw Each architecture size was more than 100 MB

**Comment by orcavia** [comment]
Same issue here, my app about ~180mb for single architecture only (base-x86_64)
