### ISSUE TITLE
SD Video is playing on top left corner in geckoview 94 

### ISSUE THREAD

**Issue by vengateshvengi03** [mozilla/geckoview#170]
I am using geckoview 94 for Android TV.SD video are playing on top-left corner ,all other area in video is black screen.But HD video playing on full screen.How to resolve i
![IMG_20210922_140119_1](https://user-images.githubusercontent.com/86402644/134335561-b0176e75-35bc-4233-8c11-a0691c73d236.jpg)
t?

**Comment by agi** [comment]
Hi @vengateshvengi03 , this repository is for GeckoView documentation, I see that you opened a bugzilla https://bugzilla.mozilla.org/show_bug.cgi?id=1731980 so I'm gonna close this one.
