### ISSUE TITLE
No UI for a datalist element's options.

### ISSUE THREAD

**Issue by lukewarlow** [mozilla/geckoview#171]
Firefox Android is afaik the only modern browser without full support for the datalist element. It would seem it lost this functionality in Firefox Android 79.

Bugzilla bug: https://bugzilla.mozilla.org/show_bug.cgi?id=1535985 (afaik Bugzilla is no longer used for tracking Geckoview bugs?)

**Comment by agi** [comment]
Hi @lukewarlow, we still use bugzilla for GeckoView (this is just for the documentation side). Thanks for bringing this to our attention, we can continue the conversation on bugzilla, I'll close this in the meantime.
