### ISSUE TITLE
WebAuthn

### ISSUE THREAD

**Issue by matthew-unum** [mozilla/geckoview#191]
Is there a way to have GeckoView work with https://webauthn.io/? I have tried to implement it myself as well as look for examples, but I have not found a way to make this work.

**Comment by jonalmeida** [comment]
@matthew-unum yes, it is possible, but know that right now GeckoView is using the [Fido2PrivilegedApiClient](https://developers.google.com/android/reference/com/google/android/gms/fido/fido2/Fido2PrivilegedApiClient) and requires any app's signing key to be put on an allowlist to use those APIs.

If they're not there the fallback method is to use the [Fido2ApiClient](https://developers.google.com/android/reference/com/google/android/gms/fido/fido2/Fido2ApiClient).

In your usage of GeckoView, you would need to implement the [`ActivityDelegate`](https://mozilla.github.io/geckoview/javadoc/mozilla-central/org/mozilla/geckoview/GeckoRuntime.ActivityDelegate.html) on the `GeckoRuntime`.

Here is [an example](https://github.com/mozilla-mobile/android-components/blob/main/components/feature/webauthn/src/main/java/mozilla/components/feature/webauthn/WebAuthnFeature.kt) of how Fenix (via Android Components) handles these requests.
