### ISSUE TITLE
Allow Mixed Content

### ISSUE THREAD

**Issue by ddsc01** [mozilla/geckoview#195]
I think older Versions did with GeckoRuntime.Settings.AllowInsecureConnections = GeckoRuntimeSettings.ALLOW_ALL
This seems no longer to work.

How can we allow GeckoView to show Mixed Content?

**Comment by jonalmeida** [comment]
This should still work. If you can provide reproducible steps for this, can you please [file a bug here](https://bugzilla.mozilla.org/enter_bug.cgi?product=GeckoView)?
