### ISSUE TITLE
Auto play video playback

### ISSUE THREAD

**Issue by giri-qs** [mozilla/geckoview#196]
I'm developing signage application with Geckoview.
Need to show images and video in slide show.
Videos are not playing automatically. 

**Need guide to enable auto play videos and you tube videos**

`
val view: GeckoView = findViewById(R.id.webview)
val session = GeckoSession()

val runtime = GeckoRuntime.create(this)
session.open(runtime)
view.setSession(session)
session.loadUri("https://example.com") 
`

**Comment by jonalmeida** [comment]
There is no API withing GeckoView that can help with this. You could consider using similar techniques to addons like [this one](https://addons.mozilla.org/en-CA/firefox/addon/video-background-play-fix/) and use the [WebExtension API](https://firefox-source-docs.mozilla.org/mobile/android/geckoview/consumer/web-extensions.html) to enable this behaviour.

**Comment by ghost** [comment]
hello, the extension you mentioned : https://addons.mozilla.org/en-CA/firefox/addon/video-background-play-fix/ is not installing with installBuiltIn or ensureBuiltIn on WebExtension API. can you please take a look.
