### ISSUE TITLE
how to change the text selection handle icon resource

### ISSUE THREAD

**Issue by HowQuitVim** [mozilla/geckoview#200]
i am building a app with geckoview,i want to know how to change the text selection raindrop icon,and the selected text foreground color,just like that
![image](https://user-images.githubusercontent.com/28687659/212715454-3671c6ea-ff6e-4830-b8a7-0c9e7494f290.png)

**Comment by jonalmeida** [comment]
My helpful co-workers recognized that this can be done by overriding the `colorAccent` resource attribute. :)

**Comment by HowQuitVim** [comment]
@jonalmeida
thank you for you answer first.
just like this ?
colors.xml:
\<color name="colorAccent"\>#0000ff\</color\>

but it does not work for me

**Comment by jonalmeida** [comment]
I'm not sure what might be the cause then. This is how we set the color is our apps as well, for example in [Firefox Focus](https://github.com/mozilla-mobile/firefox-android/blob/main/focus-android/app/src/main/res/values/colors.xml#L30).
