### ISSUE TITLE
extension problem default_locale

### ISSUE THREAD

**Issue by RoxDevvv** [mozilla/geckoview#201]
this field throw an error and extension won't work
"default_locale": "en"

how to know what supported and what not in geckoview extensions

**Comment by jonalmeida** [comment]
If you add this follow code to your gradle file, the missing locales will be include: https://searchfox.org/mozilla-central/source/mobile/android/geckoview_example/build.gradle#39-43,45

Source: https://bugzilla.mozilla.org/show_bug.cgi?id=1764929#c4
