### ISSUE TITLE
Is it possible to modify the focus color of a dom element when using tab key navigation

### ISSUE THREAD

**Issue by donpaul120** [mozilla/geckoview#205]
I've searched the documentation to see if this is possible but i haven't found anyway to do this.

<img width="372" alt="Screenshot 2023-02-02 at 13 11 48" src="https://user-images.githubusercontent.com/6430195/216321382-cbac5ecb-fd4b-4f19-bc35-7261eb50b187.png">

**Comment by abhijain2003** [comment]
Yes, it is possible to modify the focus color of a DOM element when using tab key navigation. You can use CSS to style the focus color of an element, for example:

:focus {
    outline: 3px solid blue;
}

This will set the outline color to blue when the element is focused using the tab key. You can adjust the outline color and style to your preference.

**Comment by donpaul120** [comment]
I think i'm referring to how this can be done via `GeckoSession` perhaps this is the wrong repository to ask.

I'm with the mozilla-android-components, and was hoping i could manipulate the DOM elements directly from java/kotlin.

**Comment by jonalmeida** [comment]
There is no way to modify the DOM elements directly. You can use the WebExt API to load the suggested CSS example above into all web pages.
