### ISSUE TITLE
how to limit cache size on GeckoView to 512MB

### ISSUE THREAD

**Issue by ghost** [mozilla/geckoview#210]

**Comment by makotokato** [comment]
@itsmecom 
We don't provide APIs for it. But It depends on about:config's preferences. So I guess that you may be able to [change it](https://firefox-source-docs.mozilla.org/mobile/android/geckoview/consumer/automation.html#enabling-reading-configuration-from-a-file-unconditionally) like Desktop Firefox via preferences.

**Comment by ghost** [comment]
@makotokato 
okay, can you tell me how can i change it via preferences

**Comment by makotokato** [comment]
`browser.cache.disk.capacity` and `browser.cache.memory.capacity`

**Comment by itsmecom** [comment]
how can i implement it on my code

`GeckoRuntime runtime = GeckoRuntime.getDefault(this);
   session.setNavigationDelegate(navigationDelegate);
   session.open(runtime);
   view.setSession(session);
   session.getSettings().setAllowJavascript(true);
   session.loadUri("https://www.dropbox.com/");`

**Comment by jonalmeida** [comment]
This has already been answered above: there are no APIs to do this, only preference changes in `about:config`.
