### ISSUE TITLE
Download and Upload not working on geckoview

### ISSUE THREAD

**Issue by ghost** [mozilla/geckoview#211]
Hello,
Below is my geckoview code, nothing happens when i click on download and  upload button on  the website

   ```GeckoView view = findViewById(R.id.geckoview);
      GeckoRuntime runtime = GeckoRuntime.getDefault(this);
      session.setNavigationDelegate(navigationDelegate);
      session.open(runtime);
      view.setSession(session);
      session.getSettings().setAllowJavascript(true);
      session.loadUri("https://www.dropbox.com/");```

**Comment by jonalmeida** [comment]
You need to implement the [`ContentDelegate.onExternalResponse`](https://mozilla.github.io/geckoview/javadoc/mozilla-central/org/mozilla/geckoview/GeckoSession.ContentDelegate.html#onExternalResponse(org.mozilla.geckoview.GeckoSession,org.mozilla.geckoview.WebResponse)) to handle external responses like downloads.

For uploads, you need implement the [`PromptDelegate.onFilePrompt`](https://mozilla.github.io/geckoview/javadoc/mozilla-central/org/mozilla/geckoview/GeckoSession.PromptDelegate.html#onFilePrompt(org.mozilla.geckoview.GeckoSession,org.mozilla.geckoview.GeckoSession.PromptDelegate.FilePrompt)) to delegate out to a file picker.

You can see a basic example of how to use GeckoView in this example app: https://hg.mozilla.org/mozilla-central/file/tip/mobile/android/geckoview_example

I would still recommend you consider Mozilla's Android Components as most of this is handled for you.

**Comment by ghost** [comment]
@jonalmeida atleast tell me how can i import android components and link it with my above code. please

**Comment by jonalmeida** [comment]
There is information in the project on how to get started: https://github.com/mozilla-mobile/firefox-android/tree/main/android-components

**Comment by itsmecom** [comment]
@jonalmeida i have successfully implemented PromptDelegate.FilePrompt
but i get this error :

GeckoSession : Only file URIs are supported: content://com.android.providers.downloads.documents/document

please help me with this

**Comment by jonalmeida** [comment]
The error message is telling you that you need use a file URI. You are using a content one.

**Comment by itsmecom** [comment]
@jonalmeida 
As i already mentioned that i followed the code from geckoview_example :  https://searchfox.org/mozilla-central/source/mobile/android/geckoview_example/src/main/java/org/mozilla/geckoview_example/

the existing geckoview_example code returns `content://` uri instead of `file:///` uri

please update the code on geckoview_example
