### ISSUE TITLE
Required attribute on input is not respected

### ISSUE THREAD

**Issue by srichter** [mozilla/geckoview#48]
When interacting with a form which has the "required" attribute on an input, Firefox Focus will ignore it and submit the form anyway when the input is empty. This only happens in Firefox Focus when GeckoView is enabled. The example here, or any other use of the attribute, will fail to function properly: https://developer.mozilla.org/en-US/docs/Learn/HTML/Forms/Form_validation#The_required_attribute

GeckoView 65
Focus 8.0.8
Android 8.0.1

**Comment by agi90** [comment]
Hi @srichter thanks for the report, this repo is for GeckoView documentation, our bug reports for GeckoView live on [bugzilla][0]. I opened a bug for this [there][1].

[0]: https://bugzilla.mozilla.org/buglist.cgi?product=GeckoView&component=General&resolution=---&list_id=14649234
[1]: https://bugzilla.mozilla.org/show_bug.cgi?id=1541624

**Comment by srichter** [comment]
Whoops, thanks.
