### ISSUE TITLE
How to add permissions

### ISSUE THREAD

**Issue by dipiana** [mozilla/geckoview#63]
I find it very hard / impossible to understand how to give GeckoView permission to use the microphone. I tried to google, ask in different forums but could not get an answer.
Could anybody help me with that?
My goal is to give GeckoView permission that a website uses the microphone/records.

Thanks!

**Comment by agi90** [comment]
Hi @dipiana ! you want to override `PermissionDelegate.onMediaPermissionRequest` and implement it accordingly to grant the website permission.

Javadoc: https://mozilla.github.io/geckoview/javadoc/mozilla-central/org/mozilla/geckoview/GeckoSession.PermissionDelegate.html#onMediaPermissionRequest-org.mozilla.geckoview.GeckoSession-java.lang.String-org.mozilla.geckoview.GeckoSession.PermissionDelegate.MediaSource:A-org.mozilla.geckoview.GeckoSession.PermissionDelegate.MediaSource:A-org.mozilla.geckoview.GeckoSession.PermissionDelegate.MediaCallback-

Example code: https://searchfox.org/mozilla-central/rev/29f8e6aebd2b2660b9c76858ccb0c6eaf35dd7aa/mobile/android/geckoview_example/src/main/java/org/mozilla/geckoview_example/GeckoViewActivity.java#823-857

**Comment by fluffyemily** [comment]
We are aware that this documentation is missing - it's been in the works for a while. Your issue prompted me to finish it off. See #15 and #65

**Comment by fluffyemily** [comment]
Documentation landed: https://mozilla.github.io/geckoview/consumer/docs/permissions
