### ISSUE TITLE
Some links in Readme give 404

### ISSUE THREAD

**Issue by strongSoda** [mozilla/geckoview#68]
## These are the dead links in the readme file.

GeckoView Contributor Quick Start Guide
Mozilla Central Quick Start Guide
Mozilla Central Contributor Guide
Guide to Native Debugging in Android Studio

![404](https://user-images.githubusercontent.com/30754328/61587430-faf8ac80-aba7-11e9-8efc-987256f25d11.png)

**Comment by agi90** [comment]
We should probably fix that somehow, but note that this package is the source code for this website: https://mozilla.github.io/geckoview/

**Comment by strongSoda** [comment]
I'll try and send a PR
