### ISSUE TITLE
missing license file

### ISSUE THREAD

**Issue by gnesher** [mozilla/geckoview#74]
As the title suggests, there's no LICENSE file in the repository, which reduces the usability of the component.
As I'm not certain which license Mozilla uses I couldn't create a pull req.

**Comment by fluffyemily** [comment]
So, this repo is for the documentation site only. All Mozilla licenses are kept with the code in our Mercurial repository and are [Mozilla Public License](http://mozilla.org/MPL/2.0/).

You can find the [code](https://searchfox.org/mozilla-central/source/mobile/android/geckoview) and get a copy by following the instructions on our [documentation site](https://mozilla.github.io/geckoview/contributor/mc-quick-start).

**Comment by gnesher** [comment]
Ah, I missed that, was just looking to find the license for a blog post I'm writing - wasn't aware there's a unified license for all Mozilla projects. Thanks, closing the ticket.

**Comment by gnesher** [comment]
@fluffyemily  just a quick note - the link to the documentation site you provided does not work (seems to affect the README file as well

**Comment by fluffyemily** [comment]
@gnesher bizarre, all the links in both the README and this issue work for me. I shall investigate.

For all our documentation go to
https://mozilla.github.io/geckoview/

**Comment by gnesher** [comment]
@fluffyemily I'm just getting a "This site can’t be reached The connection was reset." error
I am able to access the URL from my mobile phone though, might be a network issue

**Comment by fluffyemily** [comment]
What browser are you using? https://github.com/itchio/itch.io/issues/949 suggests that it could be a proxy/firewall problem on your end. Can you try in a Private Browsing or Incognito window to see if it loads there?

**Comment by gnesher** [comment]
I'm using Chrome and you're right, private mode solves the problem

**Comment by dllud** [comment]
Re-opening this discussion because the documentation itself needs a license.
Please add a license file to this repository to make it clear under which terms the documentation can be used and which license will be applied to contributions.

The general [Mozilla licensing page](https://www.mozilla.org/en-US/foundation/licensing/) isn't much helpful, as it points to two different licenses:
> The text of Mozilla websites is generally licensed under a Creative Commons Attribution (CC BY) or Attribution-ShareAlike (CC BY-SA) license
