### ISSUE TITLE
Page looks broken

### ISSUE THREAD

**Issue by agi90** [mozilla/geckoview#76]
Something happened to our style? I don't see any change though.

<img width="907" alt="Screen Shot 2019-08-15 at 4 09 44 PM" src="https://user-images.githubusercontent.com/4297388/63132782-2d16e780-bf77-11e9-880f-c29622e56924.png">

**Comment by Amejia481** [comment]
Seeing the same issue on different browsers. Are we pulling some styles or js files from external sources?

**Comment by agi90** [comment]
We weren't pinning the style to a version and it updated under us. It should work now.
