### ISSUE TITLE
Calling methods in android code from JS

### ISSUE THREAD

**Issue by rajdeep-pocketaces** [mozilla/geckoview#85]
I have an app which uses webview as of now for loading html based games. I use @JavascriptInterface in my activity to expose some methods to the JS code because of some requirements. But now i am planning to geckoview due to some reasons.
If anyone can lead to me to some alternatives that i can use while using geckoview to provide the same functionality, that would be great.

**Comment by snorp** [comment]
You can use a Web Extension to interact with content. More info about this can be found here: https://mozilla.github.io/geckoview/consumer/docs/web-extensions

I'll close this bug, but if you have more questions you can ask theme here or on Mozilla IRC (#mobile).
