### ISSUE TITLE
Add support for general.useragent.override.website.domain

### ISSUE THREAD

**Issue by serovar** [mozilla/geckoview#90]
For some reason, support for the general.useragent.override.website.domain option in about:config has been removed in the latest nightlies. I opened a bug on the Fenix issue tracker (https://github.com/mozilla-mobile/fenix/issues/5642), where I was told that the option is not supported in GeckoView.

This is a then a feature request to readd support for this option, since it was working before, it is supported on Gecko (it does work on Fennec, with which you want feature parity, I suppose) and there is already a general.useragent.override option that works for every website, so I don't really see why a per site implementation should not be supported.

**Comment by agi90** [comment]
In general anything in `about:config` could go away at any point, and we don't support it in any meaningful way.

Support for `general.useragent.override.website.domain` has been removed from Gecko in Bug 1513574, so that's why it doesn't work in GeckoView. No version of Firefox will support that (not even Desktop).

In the future you will be able to do this with an extension.

**Comment by filips123** [comment]
@agi90 Is there any reason why it was removed? I think that it is easier to just use `about:config` entry than the extension if you want to change user-agent for long term.

**Comment by Neustradamus** [comment]
@agi90: Any news?

There is a solution?

**Comment by fluffyemily** [comment]
> @agi90: Any news?
> 
> There is a solution?

As you can see from the commentary in [Bug 1513574](https://bugzilla.mozilla.org/show_bug.cgi?id=1513574), support for this pref was dropped in both desktop and mobile Firefox in favour of WebExtension support for user agent switching. We are not planning to reinstate that functionality as a pref inside GeckoView.

**Comment by filips123** [comment]
What is the solution then? Firefox Preview does not yet support any user agent switching extensions.

**Comment by KUKHUA** [comment]
Where is an Extension that allows you to change per domain the user agent??
