### ISSUE TITLE
Intercept network requests

### ISSUE THREAD

**Issue by sergeymild** [mozilla/geckoview#92]
Is it possible to have something like WebView.shouldInterceptRequest in GeckoView? If it is already has, could you please give some examples how to?

**Comment by snorp** [comment]
There are currently no plans to add an API like this. You may be able to do it via a Web Extension, though. There's some info on this here: https://mozilla.github.io/geckoview/consumer/docs/web-extensions

The Web Extension API you'd want to use is `webRequest`. https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/webRequest

**Comment by sergeymild** [comment]
i make like this:
manifest.json
```
{
  "manifest_version": 2,
  "name": "messaging",
  "version": "1.0",
  "description": "Example messaging web extension.",
  "content_scripts": [
    {
      "matches": ["<all_urls>"],
      "js": ["messaging.js"],
      "run_at": "document_start"
    }
  ],
  "permissions": [
    "nativeMessaging",
    "geckoViewAddons",
    "webRequest",
    "webRequestBlocking"
  ]
}
```
messaging.js
``` console.log(browser.webRequest)```
it's write what it is undefined.
What am i doing wrong?
