### ISSUE TITLE
WebRequest, WebResponse

### ISSUE THREAD

**Issue by tmdwns7809** [mozilla/geckoview#96]
I tried to fetch html by using WebRequest class and i got a WebResponse through a GeckoWebExecutor<WebResponse> object.
And then i converted the WebResponse object to a string object.
And then i loaded the string object by using loadString or loadData as a text/html mime type.
But it couldn't render the page perfectly like it couldn't print some images which was printed when i just used loadUri with a url.
Could you please tell me why this's happening and how to solve?

**Comment by snorp** [comment]
This is likely an issue with relative URIs on the page. e.g. `<img src="foo.jpg">` won't work if you load as a data URL. What's the core problem you're trying to solve by fetching the page yourself?

**Comment by tmdwns7809** [comment]
Oh, thank you so much for replying! I'm making my web page translating app. I have my dictionary data base and i know how to translate based on that. So i was going to fetch the web pages html and translate the text inside the html and print it to the screen. I just want to edit some text inside the web page before i print it to the screen with geckoview. Is there any other way that i can achieve that?

**Comment by tmdwns7809** [comment]
Do you mean loadData and loadString can't process relative URIs?

**Comment by agi90** [comment]
@tmdwns7809 I would recommend looking into using a WebExtension for this. You could read/modify the webpage content using a content script and sending the data to be translated to your app using messaging (if you can't do the translation directly in javascript), see here: http://gv.dev/consumer/docs/web-extensions

**Comment by tmdwns7809** [comment]
@agi90 Thank you so much!!! I will work on that!
